package com.tamecode.lesson7.mapper;

import com.tamecode.lesson7.entity.ZhExplore;
import com.tamecode.lesson7.entity.ZhExploreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhExploreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    long countByExample(ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int deleteByExample(ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int insert(ZhExplore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int insertSelective(ZhExplore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    List<ZhExplore> selectByExampleWithBLOBs(ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    List<ZhExplore> selectByExample(ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    ZhExplore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") ZhExplore record, @Param("example") ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ZhExplore record, @Param("example") ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int updateByExample(@Param("record") ZhExplore record, @Param("example") ZhExploreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int updateByPrimaryKeySelective(ZhExplore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ZhExplore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zh_explore
     *
     * @mbg.generated Sat Aug 15 23:20:55 CST 2020
     */
    int updateByPrimaryKey(ZhExplore record);
}